### ISSUE TITLE
Option for output

### ISSUE THREAD

**Issue by MartinNorman** [kpdecker/jsdiff#213] opened 2018-01-26 22:42 UTC
Hello,
Is it possible to control the result.
For example, I'm using diffTrimmedLines.
My data  to match is:
File1
"Hello world!
Line1
Line2"

File2
"Hello world!
Line1
Line3"

Since rows 1 and 2 are identical they will be grouped in the result as one object where count will be 2 indicating that 2 rows are identical.
Line 3 will be returned as 2 objects (one from File1 and one from file2).

What I would like is for rows 1 and 2 to be returned as separate object.
Both rows without Added and Removed.
Is this possible?

The reason is that I'm using this result for further processing that is done on row level and not having the status on each row causes problems.

**Comment by ExplodingCabbage** [comment] 2024-01-02 13:30
Dupe of https://github.com/kpdecker/jsdiff/issues/148; planned for next release.

**Closed by ExplodingCabbage** 2024-01-02 13:30 UTC
