### ISSUE TITLE
`diffWords` is not ignoring white space

### ISSUE THREAD

**Issue by klister10** [kpdecker/jsdiff#236] opened 2018-11-15 16:43 UTC
I am using `diffWords` to compare two strings, but I am having a problem. Whitespace is being included in the diff, even though I am not using `diffWordsWithSpace`. I tried switching to `diffWordsWithSpace` just to verify, and the behavior remained exactly the same

**Comment by ThomasArdal** [comment] 2020-08-31 11:06
Is it possible to fix this somehow or is there a workaround? Just experienced the same problem.

**Comment by damien-monni** [comment] 2021-02-19 11:13
Same problem for me

**Comment by varunmankal** [comment] 2021-05-12 17:18
I am facing the same problem too.

**Comment by ExplodingCabbage** [comment] 2024-01-02 20:26
Agree that this is a total mess right now. I'm gonna close this as a duplicate of https://github.com/kpdecker/jsdiff/issues/436, though, where I've got some examples of the brokenness.

**Closed by ExplodingCabbage** 2024-01-02 20:26 UTC
