### ISSUE TITLE
What does count mean in change object

### ISSUE THREAD

**Issue by dawoodaijaz97** [kpdecker/jsdiff#277] opened 2020-02-08 14:55 UTC
{ count: 27,
    added: true,
    removed: undefined,
    value:
     'is an American multinational technology company that specializes in Internet-related services and products' },
  { count: 2, value: ', ' },
I get the following change object can anyone explain this to me
what does count actually mean

**Comment by UziTech** [comment] 2020-02-22 04:07
I believe count is the number of items in the `value`.
For `diffWords` it is the number of words or non word characters (i.e. '` `', '`,`', '`-`')

**Comment by kudlav** [comment] 2023-09-11 08:24
Duplicate of https://github.com/kpdecker/jsdiff/issues/210

**Closed** 2024-01-04 16:30 UTC
