### ISSUE TITLE
"has the film started yet ?" against "has the film already started" by word result unequal "started"

### ISSUE THREAD

**Issue by polkila** [kpdecker/jsdiff#151] opened 2016-11-27 14:12 UTC
[
	{
		"count": 6,
		"value": "has the film "
	},
	{
		"count": 1,
		"removed": true,
		"value": "already"
	},
	{
		"count": 1,
		"added": true,
		"value": "started"
	},
	{
		"count": 1,
		"value": " "
	},
	{
		"count": 1,
		"removed": true,
		"value": "started"
	},
	{
		"count": 3,
		"added": true,
		"value": "yet ?"
	}
]

**Comment by PWKad** [comment] 2017-01-12 00:13
Just out of curiosity I checked in the demo and did not see what you are mentioning above, it only showed the diff properly.   http://kpdecker.github.io/jsdiff/

**Comment by ExplodingCabbage** [comment] 2023-12-20 19:55
I can't reproduce either. Maybe there was a real bug here in 2016 that got fixed? :shrug: - either way there's nothing to do without a reproducible example.

**Closed by ExplodingCabbage** 2023-12-20 19:55 UTC
