### ISSUE TITLE
Special characters

### ISSUE THREAD

**Issue by nicolasiensen** [kpdecker/jsdiff#58] opened 2015-05-13 20:46 UTC
Hi!

First of all, congrats for this awesome solution for string diffs.

I'm trying to get the diff between two words that contains special characters, very common in Portuguese and Spanish languages.

For example, the diff between ```jurídica``` and ```física``` is returning ```f``` ```jur``` ```í``` ```sica``` ```dica```, but it should recognize them as completely different words.

If I take off the special character "í" the result is two different words: ```fisica``` and ```juridica```.

Is this behavior expected?

Cheers!

**Comment by kpdecker** [comment] 2015-06-03 01:05
This is an artifact of es5 regex behaviors. We should look at the es6
Unicode regex matching and we should look at the poly fill for the interim.

**Comment by kpdecker** [comment] 2015-08-04 17:50
Duplicate of #29

**Closed by kpdecker** 2015-08-04 17:50 UTC
