### ISSUE TITLE
Is there a way to generate a git-merge style single string?

### ISSUE THREAD

**Issue by hponde** [kpdecker/jsdiff#307] opened 2020-12-23 19:32 UTC
If I have a patch and the original content, is there a way using this library to generate the single string that we see as the output of a git merge with the `<<<<<<`, `======` and `>>>>>>` markers?

**Comment by ExplodingCabbage** [comment] 2024-01-08 17:53
Pretty sure the merge code in `merge.js` is meant to be able to support this, but there are open bug reports about it, it's not documented, and I'm not totally sure how it works. I'll get back to this question once I've addressed other issues about that code and had a proper look at it...

**Comment by ExplodingCabbage** [comment] 2024-06-29 19:56
No longer planned. Closing as a dupe of https://github.com/kpdecker/jsdiff/issues/181, but I personally am not gonna tackle that; sorry!

**Closed by ExplodingCabbage** 2024-06-29 19:56 UTC
Labels: question, merge
