### ISSUE TITLE
Issue while loading large JSON file: Using JSONDIFF function

### ISSUE THREAD

**Issue by anil-manjappa** [kpdecker/jsdiff#186] opened 2017-07-15 09:40 UTC
Hi,
When try to load a large json file(>500KB), browser use to hang. I am using the JSONDIFF function from the diff algorithm.

**Comment by ExplodingCabbage** [comment] 2023-12-20 20:26
Closing as more or less a duplicate of https://github.com/kpdecker/jsdiff/issues/79 (which is also about performance when diffing large JSON texts).

**Closed by ExplodingCabbage** 2023-12-20 20:26 UTC
