### ISSUE TITLE
html support

### ISSUE THREAD

**Issue by webchaz** [kpdecker/jsdiff#48] opened 2015-02-13 20:55 UTC
Is there anyway for this to work with html, by maintaining the original markup or ignoring html tags, so that only the text is updated, but the html remains intact?

**Comment by mattsgarlata** [comment] 2015-03-08 13:42
I think this may be as simple as the code below.

```
var HtmlDiff = new diff.Diff(true)
HtmlDiff.tokenize = function(value) {
	return removeEmpty(value.split(/(<>[{}:;,]|\s+)/));
}
var diffs = HtmlDiff.diff(revision1, revision2)
```

**Comment by kpdecker** [comment] 2015-08-07 22:41
@webchaz could you elaborate on what you are looking for?

**Comment by unkw** [comment] 2015-08-25 16:15
the problem is not solved

**Comment by kpdecker** [comment] 2015-08-25 16:41
Closing in favor of #71. Moving discussion there.

**Closed by kpdecker** 2015-08-25 16:41 UTC
