### ISSUE TITLE
can't build with webpack

### ISSUE THREAD

**Issue by legendhl** [kpdecker/jsdiff#562] opened 2024-09-18 12:47 UTC
Hi, I'm trying to use this library with webpack, but it doesn't work.
```
"diff": "^7.0.0",
"ts-loader": "^9.5.1",
"typescript": "^5.6.2",
"webpack": "^5.94.0",
"webpack-cli": "^5.1.4"
```
```
webpack.config.js
module.exports = {
    entry: './src/index.ts',
    mode: 'production',
    output: {
        filename: 'bundle.js',
        path: path.resolve(__dirname, 'dist'),
        // library: 'Diff',  // doesn't work either
    },
    module: {
        rules: [
            {
                test: /\.ts$/,
                use: 'ts-loader',
                exclude: /node_modules/,
            },
        ],
    },
    resolve: {
        extensions: ['.ts'],
    },
};
```
error: 
```
assets by status 4.67 KiB [cached] 1 asset
./src/index.ts 249 bytes [built] [code generated]
./src/diff/merge.ts 6.57 KiB [built] [code generated]
./node_modules/diff/lib/index.js 8.27 KiB [built] [code generated]

ERROR in ./node_modules/diff/lib/index.js 142:31-53
Module not found: Error: Can't resolve './diff/base' in '/Volumes/Work/bulb-diff-merge2/node_modules/diff/lib'
 @ ./src/diff/merge.ts 4:15-30
 @ ./src/index.ts 4:16-39

ERROR in ./node_modules/diff/lib/index.js 147:13-40
Module not found: Error: Can't resolve './diff/character' in '/Volumes/Work/bulb-diff-merge2/node_modules/diff/lib'
 @ ./src/diff/merge.ts 4:15-30
 @ ./src/index.ts 4:16-39
```

**Comment by ExplodingCabbage** [comment] 2024-09-19 17:03
You don't include a full repro case here (no tsconfig.json and the actual import of jsdiff isn't shown), but by filling in the gaps I was able to reproduce approximately the same error and I am pretty sure the fix is to change this, in your webpack.config.js...

```
    resolve: {
        extensions: ['.ts'],
    },
```

to this:

```
    resolve: {
        extensions: ['.ts', '.js'],
    },
```

You're getting this error because `diff/lib/index.js` is a `.js` file and you've get webpack configured to only let you import .ts files.

I don't *think* jsdiff is doing anything wrong here, so I'll close this as invalid. If I'm mistaken and there's something jsdiff ought to be doing differently to avoid this error, please explain to me!

**Closed by ExplodingCabbage** 2024-09-19 17:03 UTC

**Comment by legendhl** [comment] 2024-09-20 01:57
> You don't include a full repro case here (no tsconfig.json and the actual import of jsdiff isn't shown), but by filling in the gaps I was able to reproduce approximately the same error and I am pretty sure the fix is to change this, in your webpack.config.js...
> 
> ```
>     resolve: {
>         extensions: ['.ts'],
>     },
> ```
> 
> to this:
> 
> ```
>     resolve: {
>         extensions: ['.ts', '.js'],
>     },
> ```
> 
> You're getting this error because `diff/lib/index.js` is a `.js` file and you've get webpack configured to only let you import .ts files.
> 
> I don't _think_ jsdiff is doing anything wrong here, so I'll close this as invalid. If I'm mistaken and there's something jsdiff ought to be doing differently to avoid this error, please explain to me!

Yes, you're right, it's my mistake. It works now by adding '.js'.
Thank you.
